# jobs:
#     deployment: # デプロイ詳細
#       production: # （本番）
#         branch: master # Githubはここのブランチ名見てプッシュと同時に動作開始
#     codedeploy: # CodeDeployの設定
#       MyExampleCodeDeployToCircleCI: # アプリ名
#         application_root: /
#         region: us-east-2
#         revision_location:
#           revision_type: S3
#           s3_location: # S3の設定
#             bucket: demotravis-s3 # bucket名
#             key_pattern: MyExampleCodeDeployToCircleCI-{BRANCH}-{SHORT_COMMIT}
#         deployment_group: CIrcleCI-Codedeploy # CodeDeployのデプロイグループ名
#         deployment_config: CodeDeployDefault.AllAtOnce

version: 2.1 # We must use 2.1 to make use of orbs.
orbs: # specify all orbs you want to use.
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: MyExampleCodeDeployToCircleCI # The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
          deployment-group: CIrcleCI-Codedeploy # The name of a new deployment group for the specified application.
          service-role-arn: arn:aws:iam::884871223445:instance-profile/circleCI-service-role # The service role for a deployment group.
          bundle-bucket: democircleci-s3               # The s3 bucket where an application revision will be stored.
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1} # A key under the s3 bucket where an application revision will be stored.
